name: 'Simple Webhook Trigger'
description: 'An extremely simple JavaScript action for triggering webhooks.'
author: '1ockwood'
branding:
  icon: 'radio'
  color: 'yellow'
inputs:
  webhook-url:
    description: 'The URL for the webhook.'
    required: true
  webhook-method:
    description: 'The method used for triggering the webhook, e.g., `POST`, `GET`, etc. Defaults to `POST`.'
    required: false
    default: 'POST'
runs:
  using: 'node20'
  main: 'dist/index.js'
